# Generated by Django 5.2.3 on 2025-07-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('approve_post', 'Can approve post')]},
        ),
    ]
